name: CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'yarn'

            - run: yarn install --frozen-lockfile
              env:
                  CI: true

            - name: Build
              run: yarn build --ci
              env:
                  CI: true

            - name: Lint
              run: yarn lint
              env:
                  CI: true

            - name: Typescript
              run: yarn check:ts --ci
              env:
                  CI: true

            - name: Test
              run: yarn test --ci --coverage
              env:
                  CI: true
